#! /bin/sh
#  Blink a LED 
# 
#  blink [times] [sleep]
#
GPNR="1"
TIMES=$1
SLEEP=$2
test -z $TIMES && TIMES=1
test -z $SLEEP && SLEEP=0.2

GPPATH="/sys/class/gpio"
GPIODIR="${GPPATH}/gpio${GPNR}"

# export the GPIO pin
if [ -d "${GPIODIR}" ]; then
    echo "${GPIODIR} found"
else
    echo "${GPIODIR} not found, creating it"
    echo ${GPNR} > ${GPPATH}/export
fi

echo "Initalize the GPIO direction"
echo out > ${GPIODIR}/direction

echo "Blinking loop..."
COUNTER=0
while [ $COUNTER -lt $TIMES ]; do
    echo 1 > ${GPIODIR}/value
    sleep $SLEEP
    echo 0 > ${GPIODIR}/value
    sleep $SLEEP
    COUNTER=`expr $COUNTER + 1`
done

